/**
 * Araçlar sayfası katalog dilimi (`kaynak/API.md` §19).
 */
export const trArac = {
  "arac.baslik": "Araçlar",
  "arac.aciklama":
    "Modele araç çağırma yeteneği kazandırın; her çağrı argümanlarıyla birlikte günlüğe yazılır.",
  "arac.yeni": "Yeni araç",
  "arac.sekme.araclar": "Araçlar",
  "arac.sekme.cagrilar": "Çağrı günlüğü",
  "arac.suzgec.durum": "Etkinlik",
  "arac.suzgec.tum": "Tümü",
  "arac.suzgec.etkin": "Yalnız etkin",
  "arac.suzgec.pasif": "Yalnız pasif",
  "arac.tablo.ad": "Ad",
  "arac.tablo.slug": "Slug",
  "arac.tablo.tur": "Tür",
  "arac.tablo.uc": "Uç noktası",
  "arac.tablo.etkin": "Etkinlik",
  "arac.tablo.olusturulma": "Oluşturulma",
  "arac.tablo.islem": "İşlem",
  "arac.tur.webhook": "Webhook",
  "arac.tur.yerlesik": "Yerleşik",
  "arac.eylem.duzenle": "Düzenle",
  "arac.eylem.dene": "Test et",
  "arac.eylem.sil": "Sil",
  "arac.etkin.acik": "Etkin",
  "arac.etkin.kapali": "Pasif",
  "arac.etkin.bildirim": "{ad} aracı {durum}.",
  "arac.etkin.hata.baslik": "Etkinlik güncellenemedi",
  "arac.bos.baslik": "Henüz araç yok",
  "arac.bos.aciklama":
    "Webhook araçları modele özel işlevler kazandırır; hesap makinesi ve zaman yerleşik olarak gelir.",
  "arac.liste.alinamadi": "Araçlar alınamadı",
  "arac.yeniden_dene": "Yeniden dene",
  "arac.vazgec": "Vazgeç",
  "arac.diyalog.yeni.baslik": "Yeni araç",
  "arac.diyalog.duzenle.baslik": "Aracı düzenle",
  "arac.diyalog.aciklama":
    "Webhook araçlarında uç noktası ve isteğe bağlı başlıklar kullanılır; başlık değerleri şifreli saklanır.",
  "arac.form.ad": "Ad",
  "arac.form.ad.ipucu": "En az 2 karakter.",
  "arac.form.ad.zorunlu": "Ad en az 2 karakter olmalıdır.",
  "arac.form.slug": "Slug",
  "arac.form.slug.ipucu":
    "Boş bırakılırsa addan üretilir; organizasyon içinde tekil olmalıdır ve model bu adla çağırır.",
  "arac.form.aciklama": "Açıklama",
  "arac.form.aciklama.ipucu": "Model bu metni aracın ne yaptığını anlamak için görür.",
  "arac.form.tur": "Tür",
  "arac.form.yerlesik_slug": "Yerleşik araç",
  "arac.form.uc": "Uç noktası",
  "arac.form.uc.ipucu":
    "https zorunludur (yerel izin açıkken http de kabul edilir); istek `X-Kutyai-Imza: sha256=<hmac>` başlığıyla imzalanır.",
  "arac.form.uc.zorunlu": "Webhook araçları için uç noktası zorunludur.",
  "arac.form.uc.gecersiz": "Uç noktası mutlaka https:// ya da http:// ile başlamalıdır.",
  "arac.form.basliklar": "HTTP başlıkları",
  "arac.form.basliklar.ipucu":
    "Ad–değer çiftlerini JSON nesnesi olarak yazın, örn. Authorization başlığı. Değerler yanıtlarda maskeli görünür.",
  "arac.form.basliklar.gecersiz": "Başlıklar geçerli bir JSON nesnesi değil.",
  "arac.form.basliklar.maskeli.ipucu":
    "Kayıtlı başlıklar maskeli gösterilir; boş bırakırsanız mevcut değerler korunur.",
  "arac.form.sema": "JSON şeması",
  "arac.form.sema.ipucu":
    "Araç argümanlarının şeması (`type`, `properties`, `required`). Boş bırakılırsa sunucu varsayılanı kullanılır.",
  "arac.form.sema.gecersiz": "Şema geçerli bir JSON nesnesi değil.",
  "arac.form.etkin": "Etkin",
  "arac.form.olustur": "Oluştur",
  "arac.form.kaydet": "Kaydet",
  "arac.form.bulunamadi": "Kayıt bulunamadı.",
  "arac.form.hata.baslik": "Araç kaydedilemedi",
  "arac.olustur.bildirim": "Araç oluşturuldu: {ad}",
  "arac.kaydet.bildirim": "Araç kaydedildi: {ad}",
  "arac.sil.baslik": "Aracı sil",
  "arac.sil.aciklama": "Geçmiş çağrı kayıtları korunur, yalnız araç tanımı silinir.",
  "arac.sil.soru": "{baglanti} aracı silinsin mi?",
  "arac.sil.onayla": "Sil",
  "arac.sil.bildirim": "Araç silindi.",
  "arac.sil.bulunamadi": "Kayıt bulunamadı; liste yenilendi.",
  "arac.sil.hata.baslik": "Araç silinemedi",
  "arac.dene.baslik": "Aracı test et",
  "arac.dene.aciklama":
    "Argümanlar araç şemasına göre denetlenir, çağrı çalıştırılır ve günlüğe yazılır.",
  "arac.dene.argumanlar": "Argümanlar",
  "arac.dene.arguman.json": "Argümanlar (JSON)",
  "arac.dene.arguman.json.ipucu": "Bu aracın şeması boş; argümanları JSON nesnesi olarak yazın.",
  "arac.dene.arguman.gecersiz": "Argümanlar geçerli bir JSON nesnesi değil.",
  "arac.dene.zorunlu": "{alan} alanı zorunlu.",
  "arac.dene.sayi.gecersiz": "{alan} alanı sayı olmalıdır.",
  "arac.dene.gonder": "Çalıştır",
  "arac.dene.sonuc": "Sonuç",
  "arac.dene.durum": "Durum",
  "arac.dene.gecikme": "Gecikme",
  "arac.dene.basarili": "Araç başarıyla çalıştı.",
  "arac.dene.hata.baslik": "Araç çağrısı başarısız",
  "arac.dene.gecmis": "Çağrı günlüğünde görüntüle",
  "arac.cagri.tablo.arac": "Araç",
  "arac.cagri.tablo.durum": "Durum",
  "arac.cagri.tablo.gecikme": "Gecikme",
  "arac.cagri.tablo.olusturulma": "Zaman",
  "arac.cagri.tablo.islem": "İşlem",
  "arac.cagri.durum.basarili": "Başarılı",
  "arac.cagri.durum.hata": "Hata",
  "arac.cagri.suzgec.arac": "Araç",
  "arac.cagri.suzgec.tum_araclar": "Tüm araçlar",
  "arac.cagri.suzgec.durum": "Durum",
  "arac.cagri.suzgec.tum_durumlar": "Tüm durumlar",
  "arac.cagri.suzgec.temizle": "Süzgeci temizle",
  "arac.cagri.detay": "Ayrıntı",
  "arac.cagri.detay.baslik": "Çağrı ayrıntısı",
  "arac.cagri.argumanlar": "Argümanlar",
  "arac.cagri.sonuc": "Sonuç",
  "arac.cagri.hata": "Hata",
  "arac.cagri.konusma": "Konuşma",
  "arac.cagri.arac_id": "Araç kimliği",
  "arac.cagri.panel": "Panel (test)",
  "arac.cagri.bos.baslik": "Çağrı kaydı yok",
  "arac.cagri.bos.aciklama":
    "Sohbet ya da test akışında yapılan araç çağrıları burada listelenir.",
  "arac.cagri.alinamadi": "Çağrı günlüğü alınamadı",
} as const;

export const enArac: Record<keyof typeof trArac, string> = {
  "arac.baslik": "Tools",
  "arac.aciklama":
    "Give the model tool-calling ability; every call is logged with its arguments.",
  "arac.yeni": "New tool",
  "arac.sekme.araclar": "Tools",
  "arac.sekme.cagrilar": "Call log",
  "arac.suzgec.durum": "Status",
  "arac.suzgec.tum": "All",
  "arac.suzgec.etkin": "Active only",
  "arac.suzgec.pasif": "Inactive only",
  "arac.tablo.ad": "Name",
  "arac.tablo.slug": "Slug",
  "arac.tablo.tur": "Type",
  "arac.tablo.uc": "Endpoint",
  "arac.tablo.etkin": "Status",
  "arac.tablo.olusturulma": "Created",
  "arac.tablo.islem": "Actions",
  "arac.tur.webhook": "Webhook",
  "arac.tur.yerlesik": "Built-in",
  "arac.eylem.duzenle": "Edit",
  "arac.eylem.dene": "Test",
  "arac.eylem.sil": "Delete",
  "arac.etkin.acik": "Active",
  "arac.etkin.kapali": "Inactive",
  "arac.etkin.bildirim": "{ad} is now {durum}.",
  "arac.etkin.hata.baslik": "Status could not be updated",
  "arac.bos.baslik": "No tools yet",
  "arac.bos.aciklama":
    "Webhook tools give the model custom functions; the calculator and clock ship as built-ins.",
  "arac.liste.alinamadi": "Tools could not be loaded",
  "arac.yeniden_dene": "Try again",
  "arac.vazgec": "Cancel",
  "arac.diyalog.yeni.baslik": "New tool",
  "arac.diyalog.duzenle.baslik": "Edit tool",
  "arac.diyalog.aciklama":
    "Webhook tools use an endpoint and optional headers; header values are stored encrypted.",
  "arac.form.ad": "Name",
  "arac.form.ad.ipucu": "At least 2 characters.",
  "arac.form.ad.zorunlu": "The name must be at least 2 characters.",
  "arac.form.slug": "Slug",
  "arac.form.slug.ipucu":
    "Generated from the name when left empty; must be unique in the organization and is the name the model calls.",
  "arac.form.aciklama": "Description",
  "arac.form.aciklama.ipucu": "The model reads this text to understand what the tool does.",
  "arac.form.tur": "Type",
  "arac.form.yerlesik_slug": "Built-in tool",
  "arac.form.uc": "Endpoint",
  "arac.form.uc.ipucu":
    "https is required (http is accepted when local access is allowed); the request is signed with `X-Kutyai-Imza: sha256=<hmac>`.",
  "arac.form.uc.zorunlu": "Webhook tools require an endpoint.",
  "arac.form.uc.gecersiz": "The endpoint must start with https:// or http://.",
  "arac.form.basliklar": "HTTP headers",
  "arac.form.basliklar.ipucu":
    "Write name–value pairs as a JSON object, e.g. an Authorization header. Values appear masked in responses.",
  "arac.form.basliklar.gecersiz": "Headers are not a valid JSON object.",
  "arac.form.basliklar.maskeli.ipucu":
    "Stored headers are shown masked; leave empty to keep the current values.",
  "arac.form.sema": "JSON schema",
  "arac.form.sema.ipucu":
    "Schema of the tool arguments (`type`, `properties`, `required`). Left empty, the server default is used.",
  "arac.form.sema.gecersiz": "The schema is not a valid JSON object.",
  "arac.form.etkin": "Active",
  "arac.form.olustur": "Create",
  "arac.form.kaydet": "Save",
  "arac.form.bulunamadi": "Record not found.",
  "arac.form.hata.baslik": "Tool could not be saved",
  "arac.olustur.bildirim": "Tool created: {ad}",
  "arac.kaydet.bildirim": "Tool saved: {ad}",
  "arac.sil.baslik": "Delete tool",
  "arac.sil.aciklama": "Past call records are kept; only the tool definition is deleted.",
  "arac.sil.soru": "Delete {baglanti}?",
  "arac.sil.onayla": "Delete",
  "arac.sil.bildirim": "Tool deleted.",
  "arac.sil.bulunamadi": "Record not found; the list was refreshed.",
  "arac.sil.hata.baslik": "Tool could not be deleted",
  "arac.dene.baslik": "Test tool",
  "arac.dene.aciklama":
    "Arguments are validated against the tool schema, the call is executed and logged.",
  "arac.dene.argumanlar": "Arguments",
  "arac.dene.arguman.json": "Arguments (JSON)",
  "arac.dene.arguman.json.ipucu": "This tool has no schema; write the arguments as a JSON object.",
  "arac.dene.arguman.gecersiz": "Arguments are not a valid JSON object.",
  "arac.dene.zorunlu": "{alan} is required.",
  "arac.dene.sayi.gecersiz": "{alan} must be a number.",
  "arac.dene.gonder": "Run",
  "arac.dene.sonuc": "Result",
  "arac.dene.durum": "Status",
  "arac.dene.gecikme": "Latency",
  "arac.dene.basarili": "The tool ran successfully.",
  "arac.dene.hata.baslik": "Tool call failed",
  "arac.dene.gecmis": "View in the call log",
  "arac.cagri.tablo.arac": "Tool",
  "arac.cagri.tablo.durum": "Status",
  "arac.cagri.tablo.gecikme": "Latency",
  "arac.cagri.tablo.olusturulma": "Time",
  "arac.cagri.tablo.islem": "Actions",
  "arac.cagri.durum.basarili": "Successful",
  "arac.cagri.durum.hata": "Error",
  "arac.cagri.suzgec.arac": "Tool",
  "arac.cagri.suzgec.tum_araclar": "All tools",
  "arac.cagri.suzgec.durum": "Status",
  "arac.cagri.suzgec.tum_durumlar": "All statuses",
  "arac.cagri.suzgec.temizle": "Clear filters",
  "arac.cagri.detay": "Details",
  "arac.cagri.detay.baslik": "Call details",
  "arac.cagri.argumanlar": "Arguments",
  "arac.cagri.sonuc": "Result",
  "arac.cagri.hata": "Error",
  "arac.cagri.konusma": "Conversation",
  "arac.cagri.arac_id": "Tool id",
  "arac.cagri.panel": "Panel (test)",
  "arac.cagri.bos.baslik": "No call records",
  "arac.cagri.bos.aciklama":
    "Tool calls made in chat or in the test flow are listed here.",
  "arac.cagri.alinamadi": "The call log could not be loaded",
};
