/**
 * Bilgi tabanı (RAG) sayfası katalog dilimi (`kaynak/API.md` §20).
 */
export const trBilgi = {
  "bilgi.baslik": "Bilgi Tabanı",
  "bilgi.aciklama":
    "Belgeleri parçalayıp gömer; sohbet bu parçaları kaynak olarak kullanır.",
  "bilgi.sekme.belgeler": "Belgeler",
  "bilgi.sekme.arama": "Arama",
  "bilgi.yeni": "Yeni belge",
  "bilgi.tablo.ad": "Ad",
  "bilgi.tablo.kaynak": "Kaynak",
  "bilgi.tablo.parca": "Parça",
  "bilgi.tablo.olusturulma": "Eklendi",
  "bilgi.tablo.islem": "İşlem",
  "bilgi.ayrinti": "Parçalar",
  "bilgi.tazele": "Yeniden göm",
  "bilgi.tazele.ipucu": "Parçaları güncel gömme modeliyle tazeler.",
  "bilgi.tazele.bildirim": "Belge yeniden gömüldü ({sayi} parça).",
  "bilgi.tazele.hata.baslik": "Yeniden gömme başarısız",
  "bilgi.tazele.bulunamadi": "Kayıt bulunamadı; liste yenilendi.",
  "bilgi.sil": "Sil",
  "bilgi.sil.baslik": "Belgeyi sil",
  "bilgi.sil.aciklama": "Belge ve tüm parçaları kalıcı olarak silinir.",
  "bilgi.sil.soru": "{baglanti} belgesi silinsin mi?",
  "bilgi.sil.onayla": "Sil",
  "bilgi.sil.bildirim": "Belge silindi.",
  "bilgi.sil.bulunamadi": "Kayıt bulunamadı; liste yenilendi.",
  "bilgi.sil.hata.baslik": "Belge silinemedi",
  "bilgi.bos.baslik": "Bilgi tabanı boş",
  "bilgi.bos.aciklama":
    "Gömme için kullanıma hazır bir model seçip ilk belgeyi ekleyin.",
  "bilgi.liste.alinamadi": "Belgeler alınamadı",
  "bilgi.yeniden_dene": "Yeniden dene",
  "bilgi.vazgec": "Vazgeç",
  "bilgi.kaynak.metin": "Metin",
  "bilgi.kaynak.dosya": "Dosya",
  "bilgi.kaynak.url": "URL",
  "bilgi.ekle.baslik": "Yeni belge",
  "bilgi.ekle.aciklama":
    "Belge ~800 karakterlik parçalara bölünür ve seçilen modelin gömme uç noktasıyla vektörlenir.",
  "bilgi.ekle.ad": "Belge adı",
  "bilgi.ekle.ad.zorunlu": "Belge adı zorunludur.",
  "bilgi.ekle.bdm": "Gömme modeli",
  "bilgi.ekle.bdm.ipucu": "Yalnız hazır ya da çalışıyor durumdaki modeller gömme üretebilir.",
  "bilgi.ekle.bdm.zorunlu": "Bir model seçin.",
  "bilgi.ekle.bdm.bos": "Gömme için kullanıma hazır model yok; önce BDM sayfasından bir modeli hazırlayın.",
  "bilgi.ekle.kaynak_turu": "Kaynak türü",
  "bilgi.ekle.secin": "Seçin",
  "bilgi.ekle.metin": "Metin",
  "bilgi.ekle.dosya": "Yüklenmiş dosya",
  "bilgi.ekle.metin.alan": "Belge metni",
  "bilgi.ekle.metin.ipucu": "Metin sunucuda parçalanır; boş bırakılamaz.",
  "bilgi.ekle.metin.zorunlu": "Belge metni zorunludur.",
  "bilgi.ekle.dosya.alan": "Dosya",
  "bilgi.ekle.dosya.zorunlu": "Bir dosya seçin.",
  "bilgi.ekle.dosya.bos":
    "Yüklenmiş dosya yok; önce Dosyalar sayfasından metni çıkarılabilir bir dosya yükleyin.",
  "bilgi.ekle.dosya.secin": "Dosya seçin",
  "bilgi.ekle.gonder": "Ekle",
  "bilgi.ekle.bildirim": "Belge eklendi: {ad}",
  "bilgi.ekle.hata.baslik": "Belge eklenemedi",
  "bilgi.detay.baslik": "Belge parçaları",
  "bilgi.detay.bilgileri": "Bilgiler",
  "bilgi.detay.ad": "Ad",
  "bilgi.detay.kaynak": "Kaynak",
  "bilgi.detay.parca_sayisi": "Parça sayısı",
  "bilgi.detay.olusturulma": "Eklendi",
  "bilgi.detay.dosya": "Kaynak dosya kimliği",
  "bilgi.detay.parca": "Parça {sira}",
  "bilgi.detay.token": "{sayi} token",
  "bilgi.detay.parca.yok": "Belgenin parçası yok.",
  "bilgi.detay.bulunamadi": "Kayıt bulunamadı.",
  "bilgi.arama.baslik": "Bilgi tabanında ara",
  "bilgi.arama.aciklama":
    "Sorgu gömmeye çevrilir ve en benzer parçalar kaynak olarak listelenir.",
  "bilgi.arama.sorgu": "Sorgu",
  "bilgi.arama.sorgu.ipucu": "Bilgi tabanında aranacak metin",
  "bilgi.arama.sorgu.zorunlu": "Bir sorgu yazın.",
  "bilgi.arama.ust_k": "Kaynak sayısı",
  "bilgi.arama.ust_k.ipucu": "1 ile 50 arasında; boş bırakılırsa sunucu varsayılanı kullanılır.",
  "bilgi.arama.bdm": "Gömme modeli",
  "bilgi.arama.bdm.otomatik": "Otomatik (ilk hazır model)",
  "bilgi.arama.gonder": "Ara",
  "bilgi.arama.yol": "Arama yolu",
  "bilgi.arama.yol.pgvector": "pgvector (SQL)",
  "bilgi.arama.yol.python": "Python (kosinüs)",
  "bilgi.arama.sonuc.baslik": "Kaynaklar",
  "bilgi.arama.sonuc.sayi": "{sayi} kaynak bulundu",
  "bilgi.arama.skor": "Skor",
  "bilgi.arama.belge": "Belge",
  "bilgi.arama.parca": "Parça {sira}",
  "bilgi.arama.bos.baslik": "Sonuç yok",
  "bilgi.arama.bos.aciklama": "Farklı bir sorgu deneyin ya da bilgi tabanına belge ekleyin.",
  "bilgi.arama.hata.baslik": "Arama başarısız",
  "bilgi.arama.baglam.ipucu":
    "Aramanın çalışması için kullanıma hazır ve gömme modeli tanımlı bir BDM gerekir.",
} as const;

export const enBilgi: Record<keyof typeof trBilgi, string> = {
  "bilgi.baslik": "Knowledge Base",
  "bilgi.aciklama":
    "Documents are chunked and embedded; chat uses these chunks as sources.",
  "bilgi.sekme.belgeler": "Documents",
  "bilgi.sekme.arama": "Search",
  "bilgi.yeni": "New document",
  "bilgi.tablo.ad": "Name",
  "bilgi.tablo.kaynak": "Source",
  "bilgi.tablo.parca": "Chunks",
  "bilgi.tablo.olusturulma": "Added",
  "bilgi.tablo.islem": "Actions",
  "bilgi.ayrinti": "Chunks",
  "bilgi.tazele": "Re-embed",
  "bilgi.tazele.ipucu": "Refreshes the chunks with the current embedding model.",
  "bilgi.tazele.bildirim": "Document re-embedded ({sayi} chunks).",
  "bilgi.tazele.hata.baslik": "Re-embedding failed",
  "bilgi.tazele.bulunamadi": "Record not found; the list was refreshed.",
  "bilgi.sil": "Delete",
  "bilgi.sil.baslik": "Delete document",
  "bilgi.sil.aciklama": "The document and all of its chunks are permanently deleted.",
  "bilgi.sil.soru": "Delete {baglanti}?",
  "bilgi.sil.onayla": "Delete",
  "bilgi.sil.bildirim": "Document deleted.",
  "bilgi.sil.bulunamadi": "Record not found; the list was refreshed.",
  "bilgi.sil.hata.baslik": "Document could not be deleted",
  "bilgi.bos.baslik": "The knowledge base is empty",
  "bilgi.bos.aciklama":
    "Pick a model that is ready for embedding and add your first document.",
  "bilgi.liste.alinamadi": "Documents could not be loaded",
  "bilgi.yeniden_dene": "Try again",
  "bilgi.vazgec": "Cancel",
  "bilgi.kaynak.metin": "Text",
  "bilgi.kaynak.dosya": "File",
  "bilgi.kaynak.url": "URL",
  "bilgi.ekle.baslik": "New document",
  "bilgi.ekle.aciklama":
    "The document is split into ~800 character chunks and vectorized through the selected model's embedding endpoint.",
  "bilgi.ekle.ad": "Document name",
  "bilgi.ekle.ad.zorunlu": "Document name is required.",
  "bilgi.ekle.bdm": "Embedding model",
  "bilgi.ekle.bdm.ipucu": "Only models in the ready or running state can produce embeddings.",
  "bilgi.ekle.bdm.zorunlu": "Select a model.",
  "bilgi.ekle.bdm.bos":
    "No model is ready for embedding; first prepare a model on the BDM page.",
  "bilgi.ekle.kaynak_turu": "Source type",
  "bilgi.ekle.secin": "Select",
  "bilgi.ekle.metin": "Text",
  "bilgi.ekle.dosya": "Uploaded file",
  "bilgi.ekle.metin.alan": "Document text",
  "bilgi.ekle.metin.ipucu": "The text is chunked on the server; it cannot be empty.",
  "bilgi.ekle.metin.zorunlu": "Document text is required.",
  "bilgi.ekle.dosya.alan": "File",
  "bilgi.ekle.dosya.zorunlu": "Select a file.",
  "bilgi.ekle.dosya.bos":
    "No uploaded file yet; first upload a file with extractable text on the Files page.",
  "bilgi.ekle.dosya.secin": "Select a file",
  "bilgi.ekle.gonder": "Add",
  "bilgi.ekle.bildirim": "Document added: {ad}",
  "bilgi.ekle.hata.baslik": "Document could not be added",
  "bilgi.detay.baslik": "Document chunks",
  "bilgi.detay.bilgileri": "Information",
  "bilgi.detay.ad": "Name",
  "bilgi.detay.kaynak": "Source",
  "bilgi.detay.parca_sayisi": "Chunk count",
  "bilgi.detay.olusturulma": "Added",
  "bilgi.detay.dosya": "Source file id",
  "bilgi.detay.parca": "Chunk {sira}",
  "bilgi.detay.token": "{sayi} tokens",
  "bilgi.detay.parca.yok": "The document has no chunks.",
  "bilgi.detay.bulunamadi": "Record not found.",
  "bilgi.arama.baslik": "Search the knowledge base",
  "bilgi.arama.aciklama":
    "The query is embedded and the most similar chunks are listed as sources.",
  "bilgi.arama.sorgu": "Query",
  "bilgi.arama.sorgu.ipucu": "Text to search in the knowledge base",
  "bilgi.arama.sorgu.zorunlu": "Enter a query.",
  "bilgi.arama.ust_k": "Number of sources",
  "bilgi.arama.ust_k.ipucu": "Between 1 and 50; leave empty to use the server default.",
  "bilgi.arama.bdm": "Embedding model",
  "bilgi.arama.bdm.otomatik": "Automatic (first ready model)",
  "bilgi.arama.gonder": "Search",
  "bilgi.arama.yol": "Search path",
  "bilgi.arama.yol.pgvector": "pgvector (SQL)",
  "bilgi.arama.yol.python": "Python (cosine)",
  "bilgi.arama.sonuc.baslik": "Sources",
  "bilgi.arama.sonuc.sayi": "{sayi} sources found",
  "bilgi.arama.skor": "Score",
  "bilgi.arama.belge": "Document",
  "bilgi.arama.parca": "Chunk {sira}",
  "bilgi.arama.bos.baslik": "No results",
  "bilgi.arama.bos.aciklama": "Try a different query or add a document to the knowledge base.",
  "bilgi.arama.hata.baslik": "Search failed",
  "bilgi.arama.baglam.ipucu":
    "Search requires a BDM that is ready and has an embedding model defined.",
};
