/**
 * Dosyalar sayfası katalog dilimi (`kaynak/API.md` §18).
 *
 * Anahtar düzeni `alan.alt.anahtar`; değişkenler `{ad}` biçiminde, cümle içine
 * React bağlantısı gereken yerlerde `{baglanti}` ayırıcısı kullanılır.
 */
export const trDosya = {
  "dosya.baslik": "Dosyalar",
  "dosya.aciklama":
    "Organizasyona yüklenen dosyaları yönetin; metni çıkarılan içerik sohbet eki ve bilgi tabanı kaynağı olur.",
  "dosya.yeni": "Dosya yükle",
  "dosya.ara.etiket": "Dosya ara",
  "dosya.ara.ipucu": "Dosya adına göre ara",
  "dosya.tablo.ad": "Ad",
  "dosya.tablo.tur": "Tür",
  "dosya.tablo.boyut": "Boyut",
  "dosya.tablo.metin": "Çıkarılan metin",
  "dosya.tablo.olusturulma": "Yüklenme",
  "dosya.tablo.islem": "İşlem",
  "dosya.metin.uzunluk": "{sayi} karakter",
  "dosya.metin.yok": "Metin yok",
  "dosya.indir": "İndir",
  "dosya.indir.bildirim": "{ad} indirildi.",
  "dosya.indir.hata.baslik": "Dosya indirilemedi",
  "dosya.ayrinti": "Ayrıntı",
  "dosya.sil": "Sil",
  "dosya.sil.baslik": "Dosyayı sil",
  "dosya.sil.aciklama": "Kayıt ve diskteki kopya kalıcı olarak silinir.",
  "dosya.sil.soru": "{baglanti} dosyası kalıcı olarak silinsin mi?",
  "dosya.sil.onayla": "Sil",
  "dosya.sil.bildirim": "Dosya silindi.",
  "dosya.sil.bulunamadi": "Kayıt bulunamadı; liste yenilendi.",
  "dosya.sil.hata.baslik": "Dosya silinemedi",
  "dosya.bos.baslik": "Henüz dosya yok",
  "dosya.bos.aciklama":
    "Sohbete ek olarak kullanmak için metin, JSON, CSV, PDF ya da görsel yükleyin.",
  "dosya.bos.suzgec.aciklama": "Arama ölçütüne uyan dosya yok; farklı bir ad deneyin.",
  "dosya.liste.alinamadi": "Dosyalar alınamadı",
  "dosya.yeniden_dene": "Yeniden dene",
  "dosya.vazgec": "Vazgeç",
  "dosya.yukle.baslik": "Dosya yükle",
  "dosya.yukle.aciklama":
    "Tür ve boyut denetimi sunucuda yapılır; içerik maskelenerek saklanır.",
  "dosya.yukle.dosya": "Dosya",
  "dosya.yukle.ipucu":
    "Desteklenen türler: metin, JSON, CSV, PDF ve görseller. Tam boyut sınırını sunucu ayarı belirler.",
  "dosya.yukle.secili": "Seçilen dosya: {ad}",
  "dosya.yukle.zorunlu": "Yüklenecek bir dosya seçin.",
  "dosya.yukle.gonder": "Yükle",
  "dosya.yukle.bildirim": "Dosya yüklendi: {ad}",
  "dosya.yukle.hata.baslik": "Dosya yüklenemedi",
  "dosya.detay.baslik": "Dosya ayrıntısı",
  "dosya.detay.bilgileri": "Bilgiler",
  "dosya.detay.ad": "Ad",
  "dosya.detay.mime": "MIME türü",
  "dosya.detay.boyut": "Boyut",
  "dosya.detay.sha256": "SHA-256",
  "dosya.detay.metin_uzunluk": "Metin uzunluğu",
  "dosya.detay.yukleyen": "Yükleyen (kullanıcı kimliği)",
  "dosya.detay.olusturulma": "Yüklenme",
  "dosya.detay.maskeleme.baslik": "Metin maskeli",
  "dosya.detay.maskeleme.govde":
    "Çıkarılan metin KVKK maskeleme kurallarından geçmiştir; hassas alanlar gizlenmiş olabilir.",
  "dosya.detay.metin": "Çıkarılan metin",
  "dosya.detay.metin.yok":
    "Bu türden metin çıkarılamadı (ör. taranmış PDF); dosya yine de saklanır ve ek olarak kullanılabilir.",
  "dosya.detay.bulunamadi": "Kayıt bulunamadı.",
} as const;

export const enDosya: Record<keyof typeof trDosya, string> = {
  "dosya.baslik": "Files",
  "dosya.aciklama":
    "Manage files uploaded to the organization; extracted text becomes a chat attachment and knowledge base source.",
  "dosya.yeni": "Upload file",
  "dosya.ara.etiket": "Search files",
  "dosya.ara.ipucu": "Search by file name",
  "dosya.tablo.ad": "Name",
  "dosya.tablo.tur": "Type",
  "dosya.tablo.boyut": "Size",
  "dosya.tablo.metin": "Extracted text",
  "dosya.tablo.olusturulma": "Uploaded",
  "dosya.tablo.islem": "Actions",
  "dosya.metin.uzunluk": "{sayi} characters",
  "dosya.metin.yok": "No text",
  "dosya.indir": "Download",
  "dosya.indir.bildirim": "{ad} downloaded.",
  "dosya.indir.hata.baslik": "File could not be downloaded",
  "dosya.ayrinti": "Details",
  "dosya.sil": "Delete",
  "dosya.sil.baslik": "Delete file",
  "dosya.sil.aciklama": "The record and the stored copy are permanently deleted.",
  "dosya.sil.soru": "Delete {baglanti} permanently?",
  "dosya.sil.onayla": "Delete",
  "dosya.sil.bildirim": "File deleted.",
  "dosya.sil.bulunamadi": "Record not found; the list was refreshed.",
  "dosya.sil.hata.baslik": "File could not be deleted",
  "dosya.bos.baslik": "No files yet",
  "dosya.bos.aciklama":
    "Upload text, JSON, CSV, PDF or an image to use it as a chat attachment.",
  "dosya.bos.suzgec.aciklama": "No file matches the search; try a different name.",
  "dosya.liste.alinamadi": "Files could not be loaded",
  "dosya.yeniden_dene": "Try again",
  "dosya.vazgec": "Cancel",
  "dosya.yukle.baslik": "Upload file",
  "dosya.yukle.aciklama":
    "Type and size checks run on the server; the content is stored masked.",
  "dosya.yukle.dosya": "File",
  "dosya.yukle.ipucu":
    "Supported types: text, JSON, CSV, PDF and images. The exact size limit comes from the server setting.",
  "dosya.yukle.secili": "Selected file: {ad}",
  "dosya.yukle.zorunlu": "Choose a file to upload.",
  "dosya.yukle.gonder": "Upload",
  "dosya.yukle.bildirim": "File uploaded: {ad}",
  "dosya.yukle.hata.baslik": "File could not be uploaded",
  "dosya.detay.baslik": "File details",
  "dosya.detay.bilgileri": "Information",
  "dosya.detay.ad": "Name",
  "dosya.detay.mime": "MIME type",
  "dosya.detay.boyut": "Size",
  "dosya.detay.sha256": "SHA-256",
  "dosya.detay.metin_uzunluk": "Text length",
  "dosya.detay.yukleyen": "Uploaded by (user id)",
  "dosya.detay.olusturulma": "Uploaded",
  "dosya.detay.maskeleme.baslik": "Text is masked",
  "dosya.detay.maskeleme.govde":
    "The extracted text passed through the KVKK masking rules; sensitive fields may be hidden.",
  "dosya.detay.metin": "Extracted text",
  "dosya.detay.metin.yok":
    "Text could not be extracted from this type (e.g. a scanned PDF); the file is still stored and can be used as an attachment.",
  "dosya.detay.bulunamadi": "Record not found.",
};
