/**
 * Panel kabuğu, menü, ortak etiketler ve giriş/kurulum/ayarlar metinleri.
 *
 * Anahtarlar `alan.alt.anahtar` düzeninde; `{ad}` yer tutucuları
 * `lib/dil.tsx` içindeki `t` ile doldurulur. Cümle içine React bileşeni
 * gömülecekse şablona `{baglanti}` yazılıp `t(...).split("{baglanti}")` ile parçalanır.
 */
export const trPanel = {
  // --- Genel
  "genel.baslik": "KutyAI Yönetim Paneli",
  "genel.aciklama": "KutyAI kurumsal BDM platformu yönetim paneli.",
  "genel.dil": "Dil",
  "genel.kapat": "Kapat",
  "genel.menu.ana": "Ana menü",
  "genel.menu.ac": "Menüyü aç",
  "genel.menu.kapat": "Menüyü kapat",
  "genel.cikis": "Çıkış yap",
  "genel.cikis.yapiliyor": "Çıkış yapılıyor…",
  "genel.oturum.kontrol": "Oturum kontrol ediliyor…",

  // --- Sol menü (spec §12.2 sırası)
  "menu.kontrol": "Kontrol Paneli",
  "menu.bdm": "BDM'ler",
  "menu.loglar": "Konuşma Kayıtları",
  "menu.kullanim": "Kullanım",
  "menu.kullanicilar": "Kullanıcılar",
  "menu.anahtarlar": "API Anahtarları",
  "menu.ayarlar": "Ayarlar",
  "menu.islem": "İşlem Kayıtları",

  // --- Rol, kullanıcı ve BDM durum etiketleri
  "rol.yonetici": "Yönetici",
  "rol.operator": "Operatör",
  "rol.izleyici": "İzleyici",
  "rol.son_kullanici": "Son Kullanıcı",
  "durum.aktif": "Aktif",
  "durum.beklemede": "Beklemede",
  "durum.pasif": "Pasif",
  "durum.bdm.taslak": "Taslak",
  "durum.bdm.hazir": "Hazır",
  "durum.bdm.calisiyor": "Çalışıyor",
  "durum.bdm.durdu": "Durdu",
  "durum.bdm.hata": "Hata",

  // --- Ortak kısa metinler
  "genel.yeniden_dene": "Yeniden dene",
  "genel.hazir": "hazır",
  "genel.yok": "yok",
  "genel.evet": "Evet",
  "genel.hayir": "Hayır",
  "genel.yukleniyor": "Yükleniyor…",
  "genel.geri": "Geri",
  "genel.ileri": "İleri",
  "genel.vazgec": "Vazgeç",
  "genel.eposta": "E-posta",
  "genel.parola": "Parola",
  "genel.parola_tekrar": "Parola tekrar",
  "genel.ad_soyad": "Ad soyad",
  "genel.marka_adi": "Marka adı",

  // --- Kontrol paneli (dashboard)
  "kontrol.aciklama": "Platformun genel durumu, kullanım değerleri ve son konuşmalar.",
  "kontrol.hata.baslik": "Veri alınamadı",
  "kontrol.sistem.baslik": "Sistem Durumu",
  "kontrol.sistem.aciklama": "API sunucusunun canlılık bilgisi.",
  "kontrol.sistem.ayakta": "Ayakta",
  "kontrol.sistem.surum": "Sürüm {surum}",
  "kontrol.sistem.ortam": "Ortam",
  "kontrol.sistem.zaman": "Sunucu zamanı",
  "kontrol.surucu.baslik": "Sürücü ve GPU",
  "kontrol.surucu.aciklama": "Konteyner çalışma zamanı ve hızlandırıcı durumu.",
  "kontrol.surucu.docker": "Docker {durum}",
  "kontrol.surucu.gpu": "GPU {durum}",
  "kontrol.surucu.surucu": "Sürücü: {surucu}",
  "kontrol.surucu.docker_yok.baslik": "Docker bulunamadı",
  "kontrol.surucu.docker_yok.metin":
    "Docker çalışma zamanı olmadan yerel konteyner modelleri (Ollama, vLLM, TGI) başlatılamaz.",
  "kontrol.surucu.gpu_yok.baslik": "GPU bulunamadı",
  "kontrol.surucu.gpu_yok.metin":
    "Bu sunucuda GPU yok; vLLM ve TGI gibi GPU gerektiren modeller başlatılamaz. Ollama gibi CPU uyumlu bir sağlayıcı seçin veya GPU çalışma zamanını kurun.",
  "kontrol.kullanim.baslik": "Kullanım Özeti",
  "kontrol.kullanim.aciklama": "Son 30 günün toplu kullanım değerleri.",
  "kontrol.kullanim.toplam_istek": "Toplam istek",
  "kontrol.kullanim.toplam_token": "Toplam token",
  "kontrol.kullanim.ortalama_gecikme": "Ortalama gecikme",
  "kontrol.kullanim.basarili": "Başarılı",
  "kontrol.kullanim.hatali": "Hatalı",
  "kontrol.kullanim.kota_asimi": "Kota aşımı",
  "kontrol.konusmalar.baslik": "Son Konuşmalar",
  "kontrol.konusmalar.aciklama": "En güncel beş konuşma kaydı.",
  "kontrol.konusmalar.basliksiz": "Başlıksız konuşma",
  "kontrol.konusmalar.bos.baslik": "Henüz konuşma yok",
  "kontrol.konusmalar.bos.metin":
    "Kullanıcılar sohbet etmeye başladığında kayıtlar burada listelenir.",
  "kontrol.tablo.baslik": "Başlık",
  "kontrol.tablo.kullanici": "Kullanıcı",
  "kontrol.tablo.model": "Model",
  "kontrol.tablo.mesaj": "Mesaj",
  "kontrol.tablo.tarih": "Tarih",

  // --- Giriş sayfası
  "giris.aciklama": "Yönetim paneline giriş yapın",
  "giris.eposta.ornek": "ad@sirket.com",
  "giris.giris_yap": "Giriş yap",
  "giris.kurulum.baslik": "Kurulum tamamlandı",
  "giris.kurulum.metin": "Yönetici hesabınızla giriş yapabilirsiniz.",
  "giris.hata.rol":
    "Bu hesap yönetim paneline giremez. Yönetici, operatör veya izleyici rolüyle giriş yapın.",
  "giris.hata.kimlik": "E-posta veya parola hatalı.",
  "giris.hata.genel": "Giriş yapılamadı.",

  // --- Kurulum sihirbazı
  "kurulum.baslik": "Kurulum Sihirbazı",
  "kurulum.aciklama": "Dört adımda platformu çalışır hâle getirin.",
  "kurulum.adim.sirket": "Şirket Bilgisi",
  "kurulum.adim.yonetici": "Yönetici Hesabı",
  "kurulum.adim.bdm": "İlk BDM",
  "kurulum.adim.ozet": "Özet",
  "kurulum.sirket.aciklama":
    "Panelde ve kullanıcı arayüzünde görünecek marka adını girin.",
  "kurulum.marka_adi.ornek": "Acme AI",
  "kurulum.yonetici.aciklama":
    "Bu hesap yönetici yetkisiyle oluşturulur ve panele giriş yapabilir.",
  "kurulum.ad_soyad.ornek": "Ayşe Yılmaz",
  "kurulum.eposta.ornek": "admin@sirket.com",
  "kurulum.parola.ipucu": "En az 8 karakter.",
  "kurulum.bdm.aciklama":
    "Platformun ilk modelini tanımlayın. Kurulum sonunda bağlantı doğrulanır.",
  "kurulum.saglayici.baslik": "Sağlayıcı",
  "kurulum.saglayici.hata.baslik": "Sağlayıcı listesi alınamadı",
  "kurulum.saglayici.hata.metin": "Sağlayıcı listesi alınamadı. Sunucu ayakta mı?",
  "kurulum.saglayici.gpu_notu":
    " Bu sağlayıcı GPU gerektirir; sunucuda GPU yoksa başlatma 503 surucu_yok ile başarısız olur.",
  "kurulum.saglayici.zorunlu": "Sağlayıcı seçimi zorunludur.",
  "kurulum.saglayici.yukleniyor": "Sağlayıcı listesi yükleniyor, lütfen bekleyin.",
  "kurulum.saglayici.yuklenemedi":
    "Sağlayıcı listesi alınamadı. “{dugme}” ile listeyi yükleyip tekrar deneyin.",
  "kurulum.gorunen_ad": "Görünen ad",
  "kurulum.gorunen_ad.ornek": "Yerel Llama 3",
  "kurulum.temel_adres": "Temel adres",
  "kurulum.upstream_model": "Upstream model",
  "kurulum.upstream_model.ipucu": "Sağlayıcıdaki model kimliği (ör. llama3, gpt-4o-mini).",
  "kurulum.api_anahtari": "API anahtarı",
  "kurulum.api_anahtari.ipucu": "Anahtar şifrelenerek saklanır ve bir daha gösterilmez.",
  "kurulum.ozet.aciklama":
    "Bilgileri kontrol edin. Onayladığınızda yönetici hesabı ve ilk model oluşturulur, ardından model bağlantısı doğrulanır.",
  "kurulum.ozet.yonetici": "Yönetici",
  "kurulum.ozet.model_adi": "Model adı",
  "kurulum.ozet.girildi": "Girildi",
  "kurulum.ozet.gerekmiyor": "Gerekmiyor",
  "kurulum.uyari.baslik": "Model bağlantısı doğrulanamadı",
  "kurulum.uyari.metin":
    "Yönetici hesabı ve model kaydı oluşturuldu; giriş yapıp model ayarlarını denetleyebilirsiniz.",
  "kurulum.uyari.yedek":
    "Sağlayıcı adresini, model kimliğini ve varsa API anahtarını denetleyin.",
  "kurulum.hata.alanlar": "Kurulumu tamamlamak için işaretli alanları düzeltin.",
  "kurulum.hata.genel": "Kurulum tamamlanamadı.",
  "kurulum.tamamla": "Kurulumu tamamla",
  "kurulum.giris_git": "Giriş sayfasına git",

  // --- Ayarlar sayfası
  "ayarlar.aciklama":
    "Marka, kayıt politikası, SMTP ve bakım modu; değişiklikler denetim izine yazılır.",
  "ayarlar.kaydet": "Ayarları kaydet",
  "ayarlar.kaydedildi": "Ayarlar kaydedildi.",
  "ayarlar.kaydedilemedi": "Ayarlar kaydedilemedi",
  "ayarlar.sunucudan_yenile": "Sunucudan yenile",
  "ayarlar.genel.baslik": "Genel",
  "ayarlar.genel.aciklama": "Marka adı ve kayıt politikası.",
  "ayarlar.saklama": "Saklama süresi (gün)",
  "ayarlar.saklama.ipucu": "Varsayılan {gun} gün; temizleme bu süreyi kullanır.",
  "ayarlar.saklama.hata": "Saklama süresi 1 ile {azami} gün arasında olmalıdır.",
  "ayarlar.kayit.baslik": "Kayıt açık",
  "ayarlar.kayit.anahtar": "Son kullanıcı kaydı kabul edilsin",
  "ayarlar.kayit.ipucu": "Kapalıyken {kod} yeni hesap açmaz.",
  "ayarlar.maskeleme.baslik": "Maskeleme",
  "ayarlar.maskeleme.anahtar": "Kişisel veri maskeleme etkin",
  "ayarlar.maskeleme.ipucu": "Maskeleme kayıt anında uygulanır; geçmiş kayıtlar değişmez.",
  "ayarlar.bakim.baslik": "Bakım modu",
  "ayarlar.bakim.anahtar": "Sohbet uçları bakımda",
  "ayarlar.bakim.uyari.baslik": "Bakım modu açık",
  "ayarlar.bakim.uyari.metin":
    "Bakım modu açıkken {uc1} ve {uc2} uçları {kodu} döner; sohbet geçici olarak kullanılamaz.",
  "ayarlar.smtp.baslik": "E-posta (SMTP)",
  "ayarlar.smtp.tanimli": "SMTP tanımlı",
  "ayarlar.smtp.tanimsiz": "SMTP tanımsız",
  "ayarlar.smtp.aciklama":
    "SMTP tanımlı değilken doğrulama ve sıfırlama bağlantıları panelde gösterilir.",
  "ayarlar.smtp.sunucu": "Sunucu",
  "ayarlar.smtp.sunucu.ipucu": "Boş bırakılırsa SMTP kapatılır.",
  "ayarlar.smtp.port": "Port",
  "ayarlar.smtp.port.hata": "SMTP portu 1 ile 65535 arasında olmalıdır.",
  "ayarlar.smtp.kullanici": "Kullanıcı",
  "ayarlar.smtp.sifre.ipucu":
    "Boş bırakılırsa mevcut parola değişmez; parola hiçbir zaman görüntülenmez.",
  "ayarlar.smtp.gonderen": "Gönderen adresi",
  "ayarlar.smtp.tls": "TLS",
  "ayarlar.yalniz_yazilir.ipucu": "Yalnız yazılabilir; boş bırakılırsa değişmez.",
  "ayarlar.tls.degistirme": "Değiştirme",
  "ayarlar.tls.acik": "Açık",
  "ayarlar.tls.kapali": "Kapalı",
  "ayarlar.log.baslik": "Tehlikeli bölge",
  "ayarlar.log.aciklama":
    "Saklama süresini aşan konuşma kayıtlarını kalıcı olarak siler. İşlem geri alınamaz ve yalnız yönetici tarafından yürütülebilir.",
  "ayarlar.log.yas": "Silinecek kayıt yaşı",
  "ayarlar.log.saklama_secenegi": "Saklama süresi ({gun} gün)",
  "ayarlar.log.gunden_eski": "{gun} günden eski",
  "ayarlar.log.temizle": "Kayıtları temizle",
  "ayarlar.log.onay.aciklama": "Silinen kayıtlar geri getirilemez.",
  "ayarlar.log.onay.soru": "{hedef} silinecek.",
  "ayarlar.log.hedef.saklama": "saklama süresini ({gun} gün) aşan tüm kayıtlar",
  "ayarlar.log.hedef.gun": "{gun} günden eski tüm kayıtlar",
  "ayarlar.log.kalici_sil": "Kalıcı olarak sil",
  "ayarlar.log.silindi": "{sayi} konuşma kaydı silindi.",
  "ayarlar.log.hata.baslik": "Temizlenemedi",

  // --- Bulunamadı sayfası
  "bulunamadi.baslik": "Sayfa bulunamadı",
  "bulunamadi.metin": "Aradığınız sayfa taşınmış veya hiç var olmamış olabilir.",
  "bulunamadi.don": "Kontrol paneline dön",

  // --- Ortak API hataları (lib/api.ts)
  "api.gecersiz_istek": "Gönderilen bilgiler geçersiz.",
  "api.oturum_gecersiz": "Oturum bilgisi geçersiz. Lütfen tekrar giriş yapın.",
  "api.yetki_yok": "Bu işlem için yetkiniz yok.",
  "api.bulunamadi": "Kayıt bulunamadı.",
  "api.cakisma": "Bu kayıt zaten mevcut.",
  "api.dogrulama_hatasi": "Gönderilen alanlar doğrulanamadı.",
  "api.oran_siniri": "Çok fazla istek gönderdiniz. Lütfen biraz bekleyin.",
  "api.sunucu_hatasi": "Sunucuda beklenmeyen bir hata oluştu.",
  "api.saglayici_hatasi": "Model sağlayıcısına ulaşılamadı.",
  "api.kullanilamiyor": "Servis şu anda kullanılamıyor.",
  "api.istek_tamamlanamadi": "İstek tamamlanamadı.",
  "api.beklenmeyen": "Beklenmeyen bir hata oluştu.",
  "api.baglanti_hatasi": "Sunucuya ulaşılamadı. API adresini ve bağlantınızı kontrol edin.",

  // --- Ortak doğrulama metinleri (lib/dogrulama.ts)
  "dogrulama.eposta.zorunlu": "E-posta adresi zorunludur.",
  "dogrulama.eposta.gecersiz": "Geçerli bir e-posta adresi girin.",
  "dogrulama.parola.zorunlu": "Parola zorunludur.",
  "dogrulama.parola.kisa": "Parola en az {uzunluk} karakter olmalıdır.",
  "dogrulama.parola.tekrar_zorunlu": "Parola tekrarı zorunludur.",
  "dogrulama.parola.eslesmiyor": "Parolalar eşleşmiyor.",
  "dogrulama.adres.zorunlu": "Temel adres zorunludur.",
  "dogrulama.adres.gecersiz": "Adres http:// veya https:// ile başlamalıdır.",
  "dogrulama.zorunlu": "{alan} zorunludur.",

  // --- Biçimlendirme birimleri (lib/bicim.ts)
  "bicim.saniye": "{deger} sn",
  "bicim.milisaniye": "{deger} ms",
} as const;

export const enPanel: Record<keyof typeof trPanel, string> = {
  // --- General
  "genel.baslik": "KutyAI Admin Panel",
  "genel.aciklama": "KutyAI enterprise BDM platform admin panel.",
  "genel.dil": "Language",
  "genel.kapat": "Close",
  "genel.menu.ana": "Main menu",
  "genel.menu.ac": "Open menu",
  "genel.menu.kapat": "Close menu",
  "genel.cikis": "Sign out",
  "genel.cikis.yapiliyor": "Signing out…",
  "genel.oturum.kontrol": "Checking session…",

  // --- Sidebar (spec §12.2 order)
  "menu.kontrol": "Dashboard",
  "menu.bdm": "BDMs",
  "menu.loglar": "Conversation Logs",
  "menu.kullanim": "Usage",
  "menu.kullanicilar": "Users",
  "menu.anahtarlar": "API Keys",
  "menu.ayarlar": "Settings",
  "menu.islem": "Audit Logs",

  // --- Role, user and BDM status labels
  "rol.yonetici": "Administrator",
  "rol.operator": "Operator",
  "rol.izleyici": "Viewer",
  "rol.son_kullanici": "End User",
  "durum.aktif": "Active",
  "durum.beklemede": "Pending",
  "durum.pasif": "Inactive",
  "durum.bdm.taslak": "Draft",
  "durum.bdm.hazir": "Ready",
  "durum.bdm.calisiyor": "Running",
  "durum.bdm.durdu": "Stopped",
  "durum.bdm.hata": "Error",

  // --- Shared short strings
  "genel.yeniden_dene": "Try again",
  "genel.hazir": "ready",
  "genel.yok": "missing",
  "genel.evet": "Yes",
  "genel.hayir": "No",
  "genel.yukleniyor": "Loading…",
  "genel.geri": "Back",
  "genel.ileri": "Next",
  "genel.vazgec": "Cancel",
  "genel.eposta": "E-mail",
  "genel.parola": "Password",
  "genel.parola_tekrar": "Confirm password",
  "genel.ad_soyad": "Full name",
  "genel.marka_adi": "Brand name",

  // --- Dashboard
  "kontrol.aciklama": "Overall platform status, usage figures and recent conversations.",
  "kontrol.hata.baslik": "Could not load data",
  "kontrol.sistem.baslik": "System Status",
  "kontrol.sistem.aciklama": "Liveness information for the API server.",
  "kontrol.sistem.ayakta": "Up",
  "kontrol.sistem.surum": "Version {surum}",
  "kontrol.sistem.ortam": "Environment",
  "kontrol.sistem.zaman": "Server time",
  "kontrol.surucu.baslik": "Runtime and GPU",
  "kontrol.surucu.aciklama": "Container runtime and accelerator status.",
  "kontrol.surucu.docker": "Docker {durum}",
  "kontrol.surucu.gpu": "GPU {durum}",
  "kontrol.surucu.surucu": "Runtime: {surucu}",
  "kontrol.surucu.docker_yok.baslik": "Docker not found",
  "kontrol.surucu.docker_yok.metin":
    "Local container models (Ollama, vLLM, TGI) cannot be started without a Docker runtime.",
  "kontrol.surucu.gpu_yok.baslik": "GPU not found",
  "kontrol.surucu.gpu_yok.metin":
    "This server has no GPU; models that require one, such as vLLM and TGI, cannot be started. Choose a CPU-compatible provider such as Ollama or install the GPU runtime.",
  "kontrol.kullanim.baslik": "Usage Summary",
  "kontrol.kullanim.aciklama": "Aggregate usage figures for the last 30 days.",
  "kontrol.kullanim.toplam_istek": "Total requests",
  "kontrol.kullanim.toplam_token": "Total tokens",
  "kontrol.kullanim.ortalama_gecikme": "Average latency",
  "kontrol.kullanim.basarili": "Successful",
  "kontrol.kullanim.hatali": "Failed",
  "kontrol.kullanim.kota_asimi": "Quota exceeded",
  "kontrol.konusmalar.baslik": "Recent Conversations",
  "kontrol.konusmalar.aciklama": "The five most recent conversation records.",
  "kontrol.konusmalar.basliksiz": "Untitled conversation",
  "kontrol.konusmalar.bos.baslik": "No conversations yet",
  "kontrol.konusmalar.bos.metin":
    "Records will be listed here once users start chatting.",
  "kontrol.tablo.baslik": "Title",
  "kontrol.tablo.kullanici": "User",
  "kontrol.tablo.model": "Model",
  "kontrol.tablo.mesaj": "Messages",
  "kontrol.tablo.tarih": "Date",

  // --- Sign-in page
  "giris.aciklama": "Sign in to the admin panel",
  "giris.eposta.ornek": "name@company.com",
  "giris.giris_yap": "Sign in",
  "giris.kurulum.baslik": "Setup complete",
  "giris.kurulum.metin": "You can now sign in with your administrator account.",
  "giris.hata.rol":
    "This account cannot access the admin panel. Sign in with an administrator, operator or viewer role.",
  "giris.hata.kimlik": "Incorrect e-mail or password.",
  "giris.hata.genel": "Could not sign in.",

  // --- Setup wizard
  "kurulum.baslik": "Setup Wizard",
  "kurulum.aciklama": "Get the platform up and running in four steps.",
  "kurulum.adim.sirket": "Company Details",
  "kurulum.adim.yonetici": "Administrator Account",
  "kurulum.adim.bdm": "First BDM",
  "kurulum.adim.ozet": "Summary",
  "kurulum.sirket.aciklama":
    "Enter the brand name that will appear in the panel and the user interface.",
  "kurulum.marka_adi.ornek": "Acme AI",
  "kurulum.yonetici.aciklama":
    "This account is created with administrator rights and can sign in to the panel.",
  "kurulum.ad_soyad.ornek": "Jane Doe",
  "kurulum.eposta.ornek": "admin@company.com",
  "kurulum.parola.ipucu": "At least 8 characters.",
  "kurulum.bdm.aciklama":
    "Define the platform's first model. The connection is verified at the end of setup.",
  "kurulum.saglayici.baslik": "Provider",
  "kurulum.saglayici.hata.baslik": "Could not load the provider list",
  "kurulum.saglayici.hata.metin": "Could not load the provider list. Is the server running?",
  "kurulum.saglayici.gpu_notu":
    " This provider requires a GPU; if the server has no GPU, startup fails with 503 surucu_yok.",
  "kurulum.saglayici.zorunlu": "Provider selection is required.",
  "kurulum.saglayici.yukleniyor": "The provider list is loading, please wait.",
  "kurulum.saglayici.yuklenemedi":
    "Could not load the provider list. Use “{dugme}” to load it and try again.",
  "kurulum.gorunen_ad": "Display name",
  "kurulum.gorunen_ad.ornek": "Local Llama 3",
  "kurulum.temel_adres": "Base address",
  "kurulum.upstream_model": "Upstream model",
  "kurulum.upstream_model.ipucu":
    "The model identifier at the provider (e.g. llama3, gpt-4o-mini).",
  "kurulum.api_anahtari": "API key",
  "kurulum.api_anahtari.ipucu": "The key is stored encrypted and never shown again.",
  "kurulum.ozet.aciklama":
    "Review the details. Once you confirm, the administrator account and the first model are created, then the model connection is verified.",
  "kurulum.ozet.yonetici": "Administrator",
  "kurulum.ozet.model_adi": "Model name",
  "kurulum.ozet.girildi": "Provided",
  "kurulum.ozet.gerekmiyor": "Not required",
  "kurulum.uyari.baslik": "Could not verify the model connection",
  "kurulum.uyari.metin":
    "The administrator account and the model record were created; sign in to check the model settings.",
  "kurulum.uyari.yedek":
    "Check the provider address, the model identifier and the API key, if any.",
  "kurulum.hata.alanlar": "Fix the highlighted fields to complete setup.",
  "kurulum.hata.genel": "Setup could not be completed.",
  "kurulum.tamamla": "Complete setup",
  "kurulum.giris_git": "Go to the sign-in page",

  // --- Settings page
  "ayarlar.aciklama":
    "Brand, registration policy, SMTP and maintenance mode; changes are written to the audit log.",
  "ayarlar.kaydet": "Save settings",
  "ayarlar.kaydedildi": "Settings saved.",
  "ayarlar.kaydedilemedi": "Could not save settings",
  "ayarlar.sunucudan_yenile": "Refresh from server",
  "ayarlar.genel.baslik": "General",
  "ayarlar.genel.aciklama": "Brand name and registration policy.",
  "ayarlar.saklama": "Retention period (days)",
  "ayarlar.saklama.ipucu": "Default {gun} days; cleanup uses this period.",
  "ayarlar.saklama.hata": "The retention period must be between 1 and {azami} days.",
  "ayarlar.kayit.baslik": "Registration open",
  "ayarlar.kayit.anahtar": "Accept end-user registrations",
  "ayarlar.kayit.ipucu": "While off, {kod} does not create new accounts.",
  "ayarlar.maskeleme.baslik": "Masking",
  "ayarlar.maskeleme.anahtar": "Personal data masking enabled",
  "ayarlar.maskeleme.ipucu": "Masking is applied at write time; existing records stay as they are.",
  "ayarlar.bakim.baslik": "Maintenance mode",
  "ayarlar.bakim.anahtar": "Chat endpoints under maintenance",
  "ayarlar.bakim.uyari.baslik": "Maintenance mode is on",
  "ayarlar.bakim.uyari.metin":
    "While maintenance mode is on, {uc1} and {uc2} return {kodu}; chat is temporarily unavailable.",
  "ayarlar.smtp.baslik": "E-mail (SMTP)",
  "ayarlar.smtp.tanimli": "SMTP configured",
  "ayarlar.smtp.tanimsiz": "SMTP not configured",
  "ayarlar.smtp.aciklama":
    "While SMTP is not configured, verification and reset links are shown in the panel.",
  "ayarlar.smtp.sunucu": "Server",
  "ayarlar.smtp.sunucu.ipucu": "Leave blank to turn SMTP off.",
  "ayarlar.smtp.port": "Port",
  "ayarlar.smtp.port.hata": "The SMTP port must be between 1 and 65535.",
  "ayarlar.smtp.kullanici": "Username",
  "ayarlar.smtp.sifre.ipucu":
    "If left blank the current password stays; the password is never displayed.",
  "ayarlar.smtp.gonderen": "Sender address",
  "ayarlar.smtp.tls": "TLS",
  "ayarlar.yalniz_yazilir.ipucu": "Write-only; unchanged if left blank.",
  "ayarlar.tls.degistirme": "Keep unchanged",
  "ayarlar.tls.acik": "On",
  "ayarlar.tls.kapali": "Off",
  "ayarlar.log.baslik": "Danger zone",
  "ayarlar.log.aciklama":
    "Permanently deletes conversation records older than the retention period. The action cannot be undone and only an administrator can perform it.",
  "ayarlar.log.yas": "Age of records to delete",
  "ayarlar.log.saklama_secenegi": "Retention period ({gun} days)",
  "ayarlar.log.gunden_eski": "Older than {gun} days",
  "ayarlar.log.temizle": "Clear records",
  "ayarlar.log.onay.aciklama": "Deleted records cannot be restored.",
  "ayarlar.log.onay.soru": "{hedef} will be deleted.",
  "ayarlar.log.hedef.saklama": "all records older than the retention period ({gun} days)",
  "ayarlar.log.hedef.gun": "all records older than {gun} days",
  "ayarlar.log.kalici_sil": "Delete permanently",
  "ayarlar.log.silindi": "{sayi} conversation records deleted.",
  "ayarlar.log.hata.baslik": "Could not clear",

  // --- Not-found page
  "bulunamadi.baslik": "Page not found",
  "bulunamadi.metin": "The page you are looking for may have moved or may never have existed.",
  "bulunamadi.don": "Back to the dashboard",

  // --- Shared API errors (lib/api.ts)
  "api.gecersiz_istek": "The submitted information is invalid.",
  "api.oturum_gecersiz": "Your session is invalid. Please sign in again.",
  "api.yetki_yok": "You do not have permission for this action.",
  "api.bulunamadi": "Record not found.",
  "api.cakisma": "This record already exists.",
  "api.dogrulama_hatasi": "The submitted fields could not be validated.",
  "api.oran_siniri": "Too many requests. Please wait a moment.",
  "api.sunucu_hatasi": "An unexpected server error occurred.",
  "api.saglayici_hatasi": "Could not reach the model provider.",
  "api.kullanilamiyor": "The service is currently unavailable.",
  "api.istek_tamamlanamadi": "The request could not be completed.",
  "api.beklenmeyen": "An unexpected error occurred.",
  "api.baglanti_hatasi": "Could not reach the server. Check the API address and your connection.",

  // --- Shared validation messages (lib/dogrulama.ts)
  "dogrulama.eposta.zorunlu": "E-mail address is required.",
  "dogrulama.eposta.gecersiz": "Enter a valid e-mail address.",
  "dogrulama.parola.zorunlu": "Password is required.",
  "dogrulama.parola.kisa": "Password must be at least {uzunluk} characters.",
  "dogrulama.parola.tekrar_zorunlu": "Password confirmation is required.",
  "dogrulama.parola.eslesmiyor": "Passwords do not match.",
  "dogrulama.adres.zorunlu": "Base address is required.",
  "dogrulama.adres.gecersiz": "The address must start with http:// or https://.",
  "dogrulama.zorunlu": "{alan} is required.",

  // --- Format units (lib/bicim.ts)
  "bicim.saniye": "{deger} s",
  "bicim.milisaniye": "{deger} ms",
};
