{{- /*
ServiceAccount (spec §11). Tüm pod'lar bunu kullanır. Uygulama Kubernetes
API'sini kullanmaz (BDM konteynerleri docker soketi üzerinden yönetilir),
bu yüzden token varsayılan olarak bağlanmaz (`serviceAccount.automountToken`).
*/ -}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kutyai.serviceAccountAd" . }}
  namespace: {{ include "kutyai.namespace" . }}
  labels:
    {{- include "kutyai.etiketler" (dict "kok" $ "bilesen" "arka-uc") | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
{{- end }}
