"""Gozlem logunu ham cikti dosyalarindan (degistirmeden) uretir."""

from __future__ import annotations

import pathlib

KOK = pathlib.Path(__file__).resolve().parents[3]
GECICI = KOK / "kaynak" / "testler" / "gecici"
HEDEF = KOK / "kaynak" / "testler" / "modeller-log.md"


def bol(dosya: str, bas: int, bit: int) -> str:
    satirlar = (GECICI / dosya).read_text(encoding="utf-8").splitlines()
    return "\n".join(satirlar[bas - 1 : bit])


P: list[str] = []
ekle = P.append

ekle("# modeller gözlem logu — 2026-09-12")
ekle("")
ekle("## Kapsam")
ekle("- API.md §8 (Model kataloğu: `/modeller`, `/saglayicilar`, `/bdm` CRUD + `/kopyala`), §1 (hata zarfı), §2 (`Bdm`, `BdmOzet` tipleri)")
ekle("- spec §4.4 (`izinli_modeller`, `boş=tümü`), §4.5 (`bdm` tablosu), §7.3 (`arkauc/app/api/modeller.py`)")
ekle("- Denetlenen birim: `arkauc/app/api/modeller.py` + hizmet katmanı `bdm_listesi/katalog.py`, `bdm_listesi/saglayicilar.py`")
ekle("- Yöntem: canlı backend (`uvicorn arkauc.app.main:app --port 8102`, geçici SQLite) üzerinden HTTP. Ürün kodu değiştirilmedi.")
ekle("- Fikstür: `kaynak/testler/betikler/modeller_*.py` betikleri; BDM durumları (`hazir`, `calisiyor`, `durdu`, `hata`, `taslak`) `durum` alanı uçlardan yazılamadığı için geçici veritabanında doğrudan `UPDATE bdm SET durum=...` ile kuruldu.")
ekle("")
ekle("Ortam değişkenleri (tüm komutlarda):")
ekle("")
ekle("````")
ekle("KUTYAI_VERITABANI_URL=sqlite+aiosqlite:///E:/kutyai-app/kaynak/testler/gecici/modeller.db")
ekle("KUTYAI_GIZLI_ANAHTAR=gozlem-gizli-anahtar")
ekle("KUTYAI_SIFRELEME_ANAHTARI=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=")
ekle("````")
ekle("")
ekle("## Koşulan komutlar")
ekle("")

ekle("### 1) `./.venv/Scripts/python.exe kaynak/testler/betikler/modeller_00_kur.py` (fikstür)")
ekle("- Beklenen: kurulum `201`, 6 BDM oluşur, durumlar yazılır, API anahtarları üretilir.")
ekle("- Gerçek çıktı (kırpıldı):")
ekle("")
ekle("````")
ekle(bol("00_kur.txt", 1, 41))
ekle("````")
ekle("")
ekle("````")
ekle(bol("00_kur.txt", 226, 259))
ekle("````")
ekle("- Sonuç: GEÇTİ")
ekle("")

ekle("### 2) `./.venv/Scripts/python.exe kaynak/testler/betikler/modeller_12_ozet.py`")
ekle("- Beklenen: `/modeller` yalnız `hazir|calisiyor` döndürür; anahtarın izin listesi süzülür; kimliksiz `401`.")
ekle("- Gerçek çıktı:")
ekle("")
ekle("````")
ekle(bol("12_ozet.txt", 1, 9))
ekle("````")
ekle("- Sonuç: GEÇTİ (durum süzgeci ve izin listesi doğru; `izinli_modeller=[]` = tümü, spec §4.4 ile uyumlu)")
ekle("")

ekle("### 3) `./.venv/Scripts/python.exe kaynak/testler/betikler/modeller_01_liste.py` (tam gövde, yönetici)")
ekle("- Beklenen: `BdmOzet` alan kümesi API.md §2 ile birebir.")
ekle("- Gerçek çıktı (yalnız yönetici bloğu):")
ekle("")
ekle("````")
ekle(bol("01_liste.txt", 35, 81))
ekle("````")
ekle("- Sonuç: GEÇTİ")
ekle("")

ekle("### 4) `./.venv/Scripts/python.exe kaynak/testler/betikler/modeller_02_sohbet_suzgec.py`")
ekle("- Beklenen: izin listesinde olmayan model için `/sohbet` reddeder (`403 yetki_yok`).")
ekle("- Gerçek çıktı:")
ekle("")
ekle("````")
ekle(bol("02_sohbet_suzgec.txt", 1, 54))
ekle("````")
ekle("- Sonuç: GEÇTİ (hem `bdm_id` hem `bdm_slug` yolu 403; süzgeç atlatılamıyor)")
ekle("")

ekle("### 5) `./.venv/Scripts/python.exe kaynak/testler/betikler/modeller_09_akis.py`")
ekle("- Beklenen: `/sohbet/akis` de aynı süzgeci uygular.")
ekle("- Gerçek çıktı:")
ekle("")
ekle("````")
ekle(bol("09_akis.txt", 1, 52))
ekle("````")
ekle("- Sonuç: GEÇTİ (SSE ucu da `403 yetki_yok`)")
ekle("")

ekle("### 6) `./.venv/Scripts/python.exe kaynak/testler/betikler/modeller_03_sizinti.py`")
ekle("- Beklenen: upstream anahtarı hiçbir yanıtta ham hâlde görünmez; `PATCH` sonrası da maskeli kalır.")
ekle("- Gerçek çıktı (PATCH bloğu ve tarama):")
ekle("")
ekle("````")
ekle(bol("03_sizinti.txt", 313, 339))
ekle("````")
ekle("")
ekle("````")
ekle(bol("03_sizinti.txt", 461, 477))
ekle("````")
ekle("- Sonuç: GEÇTİ (`sk-c***7890` maskesi tüm `Bdm` gövdelerinde sabit; ham anahtar `sk-cokgizli-GOZLEM-1234567890` ve `cokgizli` hiçbir yanıtta yok)")
ekle("")

ekle("### 7) `./.venv/Scripts/python.exe kaynak/testler/betikler/modeller_04_silme.py`")
ekle("- Beklenen: `durum=calisiyor` iken `409`; ilişkili konuşması olan BDM silinirken veri bütünlüğü korunur.")
ekle("- Gerçek çıktı (çalışan BDM):")
ekle("")
ekle("````")
ekle(bol("04_silme.txt", 1, 13))
ekle("````")
ekle("")
ekle("- Gerçek çıktı (konuşması olan BDM — silme öncesi konuşmalar):")
ekle("")
ekle("````")
ekle(bol("04_silme.txt", 27, 53))
ekle("````")
ekle("")
ekle("- Gerçek çıktı (silme isteği ve sonrası):")
ekle("")
ekle("````")
ekle(bol("04_silme.txt", 91, 165))
ekle("````")
ekle("")
ekle("````")
ekle(bol("04_silme.txt", 170, 171))
ekle("````")
ekle("- Sonuç: KALDI — `durum=calisiyor` 409 doğru; ancak konuşması olan BDM için `204` döndü ve `bdm_id=2` işaret eden 2 konuşma satırı (her biri 1 mesajlı) yetim kaldı.")
ekle("")

ekle("### 8) `./.venv/Scripts/python.exe kaynak/testler/betikler/modeller_15_slug_ozet.py`")
ekle("- Beklenen: aynı slug iki kez `409 cakisma`; Türkçe karakterler doğru sadeleşir.")
ekle("- Gerçek çıktı (betik daha önce de koşulduğu için slug sonekleri ilerlemiş durumda; aynı slug için ilk deneme 201, ikinci deneme 409):")
ekle("")
ekle("````")
ekle(bol("15_slug_ozet.txt", 1, 8))
ekle("````")
ekle("")
ekle("- İlk koşunun ham çıktısı (çakışma gövdesi):")
ekle("")
ekle("````")
ekle(bol("05_slug.txt", 28, 39))
ekle("````")
ekle("- Sonuç: GEÇTİ (`409 cakisma`, `ayrinti.alan=slug`; `Şirket İçi Çözüm Aracı` → `sirket-ici-cozum-araci`, `ĞÜŞİÖÇ ıİğüşöç` → `gusioc-iigusoc`)")
ekle("")

ekle("### 9) `./.venv/Scripts/python.exe kaynak/testler/betikler/modeller_06_saglayici_yetki.py`")
ekle("- Beklenen: `GET /saglayicilar` kimliksiz `200`, 7 kayıt, alanlar API.md §8 ile birebir.")
ekle("- Gerçek çıktı (7. kayıt + sayım + alan denetimi):")
ekle("")
ekle("````")
ekle(bol("06_saglayici_yetki.txt", 79, 98))
ekle("````")
ekle("- Sonuç: GEÇTİ")
ekle("")

ekle("### 10) `./.venv/Scripts/python.exe kaynak/testler/betikler/modeller_13_yetki_ozet.py`")
ekle("- Beklenen: anonim `401`; `son_kullanici` yazma/silme/kopyalamada `403`; `operator` silme/kopyalamada `403`, oluşturma/güncellemede yetkili.")
ekle("- Gerçek çıktı:")
ekle("")
ekle("````")
ekle(bol("13_yetki_ozet.txt", 1, 20))
ekle("````")
ekle("- Sonuç: GEÇTİ (beklenen tek istisna: `GET /modeller` bilinçli olarak sohbet istemcisine açık)")
ekle("")

ekle("### 11) `./.venv/Scripts/python.exe kaynak/testler/betikler/modeller_07_openapi.py`")
ekle("- Beklenen: API.md §8'deki 7 uç; fazladan uç veya parametre yok.")
ekle("- Gerçek çıktı:")
ekle("")
ekle("````")
ekle(bol("07_openapi.txt", 1, 19))
ekle("````")
ekle("- Sonuç: KALDI — uçlar birebir, ancak `GET /bdm` sözleşmede olmayan `arama` sorgu parametresi kabul ediyor.")
ekle("")

ekle("### 12) `./.venv/Scripts/python.exe kaynak/testler/betikler/modeller_08_kenar.py`")
ekle("- Beklenen: `arama` dışındaki davranışlar sözleşmeye uygun (`404 bulunamadi`, `400 dogrulama_hatasi`, iptal anahtar `401`).")
ekle("- Gerçek çıktı (kırpıldı):")
ekle("")
ekle("````")
ekle(bol("08_kenar.txt", 1, 3))
ekle("")
ekle(bol("08_kenar.txt", 30, 43))
ekle("")
ekle(bol("08_kenar.txt", 68, 84))
ekle("")
ekle(bol("08_kenar.txt", 102, 117))
ekle("````")
ekle("- Sonuç: GEÇTİ")
ekle("")

ekle("### 13) `./.venv/Scripts/python.exe kaynak/testler/betikler/modeller_10_yetim_etki.py`")
ekle("- Beklenen: yetim konuşma kalırsa kullanıcı/denetim uçlarında görünür etkisi ölçülür.")
ekle("- Gerçek çıktı:")
ekle("")
ekle("````")
ekle(bol("10_yetim_etki.txt", 1, 73))
ekle("````")
ekle("- Sonuç: KALDI — silinen BDM'in konuşması `GET /sohbet/konusmalar/{id}` ile `404` dönerken `GET /loglar/konusmalar` listesinde `bdm_ad: null` ile duruyor.")
ekle("")

ekle("### 14) `./.venv/Scripts/python.exe kaynak/testler/betikler/modeller_11_alanlar.py`")
ekle("- Beklenen: `Bdm` ve `BdmOzet` alan kümeleri API.md §2/§8 ile birebir.")
ekle("- Gerçek çıktı:")
ekle("")
ekle("````")
ekle(bol("11_alanlar.txt", 1, 10))
ekle("````")
ekle("- Sonuç: GEÇTİ")
ekle("")

ekle("## Bulgular")
ekle("")
ekle("- [BLOCKER] `arkauc/app/api/modeller.py:154-169`, `bdm_listesi/katalog.py:202-204` — `DELETE /bdm/{id}` ilişkili `konusma`/`mesaj` satırları varken `204` dönüyor ve satırları yetim bırakıyor (sessiz veri bütünlüğü kaybı). Şema `konusma.bdm_id` için `ondelete=\"RESTRICT\"` bildiriyor (`bdm_veritabani/modeller.py:248`), ancak motor SQLite'ta `PRAGMA foreign_keys` hiç açılmıyor (`bdm_veritabani/oturum.py:35`, kanıt: `PRAGMA foreign_keys = 0`) ve `bdm_sil` yalnız `oturum.delete(bdm)` çağırıyor; ilişki denetimi ya da kaskad yok. Beklenen: ilişkili kaydı olan BDM ya reddedilmeli (`409`) ya da bağlı konuşmalar birlikte silinmeli; hiçbir durumda var olmayan `bdm_id`'ye işaret eden satır kalmamalı. Yeniden üretme: (1) bir BDM içeren konuşma oluştur (`POST /sohbet` başarısız da olsa `konusma` satırı yazılıyor), (2) `DELETE /bdm/{id}` → `204`, (3) `SELECT k.id, k.bdm_id FROM konusma k LEFT JOIN bdm b ON b.id=k.bdm_id WHERE b.id IS NULL` → yetim satırlar. [INFERENCE] Aynı istek PostgreSQL'de FK kısıtı nedeniyle `IntegrityError` üretip genel işleyiciden `500 sunucu_hatasi` dönecektir (bu ortamda Postgres koşulmadı); her iki durumda da sözleşmedeki `204`/`409` davranışı sağlanmıyor.")
ekle("- [MINOR] `arkauc/app/api/modeller.py:70` — `GET /bdm` sözleşmede olmayan `arama` sorgu parametresini kabul ediyor; API.md §8 `GET /bdm` için yalnız `Bdm[]` diyor, spec §7.3 de parametre saymıyor. Fazladan özellik de sözleşme ihlalidir. Kanıt: `GET /bdm?arama=Slug Catismasi` → `200` + 1 kayıt; OpenAPI'de `params=[('arama','query',False)]`. Yeniden üretme: `GET /api/v1/bdm?arama=<metin>`.")
ekle("- [MINOR] `arkauc/app/servisler/upstream.py:195` (kapsam: sohbet/hazırlama; `/sohbet` yoklamasında görüldü) — `502` hata zarfının `ayrinti.govde` alanı upstream yanıt gövdesini olduğu gibi istemciye taşıyor. OpenAI'nin hata mesajı anahtarın ilk 8 karakterini (`sk-cokgi*****************7890`) açığa çıkarırken ürünün kendi maskesi `sk-c***7890`. Ham anahtar sızmıyor (`sk-cokgizli-GOZLEM-1234567890` ve `cokgizli` taraması temiz) ama maskeleme politikasından daha geniş bir açığa çıkarma. Yeniden üretme: geçersiz upstream anahtarlı bir BDM ile `POST /sohbet` → `502` gövdesi.")
ekle("")
ekle("### Kapsam dışı gözlemler (modeller.py dışı, ekibe bilgi)")
ekle("- `POST /kimlik/panel-giris` yanlış parolada `401` `gecersiz_kimlik_bilgisi` döndürüyor; bu kod API.md §1'in 401 listesinde (`kimlik_gerekli`, `jeton_gecersiz`, `jeton_suresi_doldu`, `anahtar_gecersiz`) yok. Kanıt: komut 8'in son satırları.")
ekle("- `GET /sohbet/konusmalar` yanıtı API.md §9'daki `{toplam, kayitlar}` yerine ek `sayfa`/`boyut` alanları içeriyor; yetim konuşmalar `bdm_ad: null` olarak listeleniyor. Kanıt: komut 5 ve 13.")
ekle("")
ekle("## Özet")
ekle("")
ekle("**3 bulgu (1 BLOCKER, 0 MAJOR, 2 MINOR)** + 2 kapsam dışı gözlem.")
ekle("")
ekle("BLOCKER: konuşması olan bir BDM `DELETE /bdm/{id}` ile `204` dönerek siliniyor ve bağlı `konusma`/`mesaj` satırları var olmayan `bdm_id`'ye işaret ederek yetim kalıyor (FK `RESTRICT` bildirilmiş olmasına rağmen SQLite'ta FK zorlaması kapalı).")
ekle("")

HEDEF.write_text("\n".join(P).rstrip() + "\n", encoding="utf-8")
print(f"yazildi: {HEDEF} ({len(P)} satir)")
